// <auto-generated>
//     This file was automatically generated on 15 January 2026 at 20:26:57 UTC.
//     Any manual changes may cause errors and will be overwritten when regenerated.
// </auto-generated>

#pragma warning disable IDE0130
namespace Firell.Standards;
#pragma warning restore IDE0130

public partial record CurrencyInfo
{
    /// <summary>
    /// Gold
    /// </summary>
    public static CurrencyInfo Gold { get; } = new CurrencyInfo
    {
        CommonName = "Gold",
        NativeName = "Gold",
        OfficialName = "Gold",
        Symbol = null,
        NumericCode = "959",
        AlphabeticCode = "XAU",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Palladium
    /// </summary>
    public static CurrencyInfo Palladium { get; } = new CurrencyInfo
    {
        CommonName = "Palladium",
        NativeName = "Palladium",
        OfficialName = "Palladium",
        Symbol = null,
        NumericCode = "964",
        AlphabeticCode = "XPD",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Platinum
    /// </summary>
    public static CurrencyInfo Platinum { get; } = new CurrencyInfo
    {
        CommonName = "Platinum",
        NativeName = "Platinum",
        OfficialName = "Platinum",
        Symbol = null,
        NumericCode = "962",
        AlphabeticCode = "XPT",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Silver
    /// </summary>
    public static CurrencyInfo Silver { get; } = new CurrencyInfo
    {
        CommonName = "Silver",
        NativeName = "Silver",
        OfficialName = "Silver",
        Symbol = null,
        NumericCode = "961",
        AlphabeticCode = "XAG",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };
}
