// <auto-generated>
//     This file was automatically generated on 15 January 2026 at 20:26:57 UTC.
//     Any manual changes may cause errors and will be overwritten when regenerated.
// </auto-generated>

#pragma warning disable IDE0130
namespace Firell.Standards;
#pragma warning restore IDE0130

public partial record CurrencyInfo
{
    /// <summary>
    /// Afghan Afghani
    /// </summary>
    public static CurrencyInfo AfghanAfghani { get; } = new CurrencyInfo
    {
        CommonName = "Afghani",
        NativeName = "افغانی افغانستان",
        OfficialName = "Afghan Afghani",
        Symbol = "؋",
        NumericCode = "971",
        AlphabeticCode = "AFN",
        Countries = new Dictionary<string, string>
        {
            ["AFG"] = "Islamic Republic of Afghanistan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Albanian Lek
    /// </summary>
    public static CurrencyInfo AlbanianLek { get; } = new CurrencyInfo
    {
        CommonName = "Lek",
        NativeName = "Leku Shqiptar",
        OfficialName = "Albanian Lek",
        Symbol = "L",
        NumericCode = "008",
        AlphabeticCode = "ALL",
        Countries = new Dictionary<string, string>
        {
            ["ALB"] = "Republic of Albania",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Algerian Dinar
    /// </summary>
    public static CurrencyInfo AlgerianDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "دينار جزائري",
        OfficialName = "Algerian Dinar",
        Symbol = "د.ج",
        NumericCode = "012",
        AlphabeticCode = "DZD",
        Countries = new Dictionary<string, string>
        {
            ["DZA"] = "People's Democratic Republic of Algeria",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Angolan Kwanza
    /// </summary>
    public static CurrencyInfo AngolanKwanza { get; } = new CurrencyInfo
    {
        CommonName = "Kwanza",
        NativeName = "Kwanza Angolano",
        OfficialName = "Angolan Kwanza",
        Symbol = "Kz",
        NumericCode = "973",
        AlphabeticCode = "AOA",
        Countries = new Dictionary<string, string>
        {
            ["AGO"] = "Republic of Angola",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Argentine Peso
    /// </summary>
    public static CurrencyInfo ArgentinePeso { get; } = new CurrencyInfo
    {
        CommonName = "Peso",
        NativeName = "Peso Argentino",
        OfficialName = "Argentine Peso",
        Symbol = "$",
        NumericCode = "032",
        AlphabeticCode = "ARS",
        Countries = new Dictionary<string, string>
        {
            ["ARG"] = "Argentine Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Armenian Dram
    /// </summary>
    public static CurrencyInfo ArmenianDram { get; } = new CurrencyInfo
    {
        CommonName = "Dram",
        NativeName = "հայկական դրամ",
        OfficialName = "Armenian Dram",
        Symbol = "֏",
        NumericCode = "051",
        AlphabeticCode = "AMD",
        Countries = new Dictionary<string, string>
        {
            ["ARM"] = "Republic of Armenia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Aruban Florin
    /// </summary>
    public static CurrencyInfo ArubanFlorin { get; } = new CurrencyInfo
    {
        CommonName = "Florin",
        NativeName = "Florin Arubiano",
        OfficialName = "Aruban Florin",
        Symbol = "ƒ",
        NumericCode = "533",
        AlphabeticCode = "AWG",
        Countries = new Dictionary<string, string>
        {
            ["ABW"] = "Aruba",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Australian Dollar
    /// </summary>
    public static CurrencyInfo AustralianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Australian Dollar",
        OfficialName = "Australian Dollar",
        Symbol = "$",
        NumericCode = "036",
        AlphabeticCode = "AUD",
        Countries = new Dictionary<string, string>
        {
            ["AUS"] = "Commonwealth of Australia",
            ["CXR"] = "Territory of Christmas Island",
            ["CCK"] = "Territory of the Cocos (Keeling) Islands",
            ["HMD"] = "Heard Island and McDonald Islands",
            ["KIR"] = "Independent and Sovereign Republic of Kiribati",
            ["NRU"] = "Republic of Nauru",
            ["NFK"] = "Territory of Norfolk Island",
            ["PCN"] = "Pitcairn Group of Islands",
            ["SLB"] = "Solomon Islands",
            ["TUV"] = "Tuvalu",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Azerbaijani Manat
    /// </summary>
    public static CurrencyInfo AzerbaijaniManat { get; } = new CurrencyInfo
    {
        CommonName = "Manat",
        NativeName = "Azərbaycan Manatı",
        OfficialName = "Azerbaijani Manat",
        Symbol = "₼",
        NumericCode = "944",
        AlphabeticCode = "AZN",
        Countries = new Dictionary<string, string>
        {
            ["AZE"] = "Republic of Azerbaijan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Bahamian Dollar
    /// </summary>
    public static CurrencyInfo BahamianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Bahama Dollar",
        OfficialName = "Bahamian Dollar",
        Symbol = "$",
        NumericCode = "044",
        AlphabeticCode = "BSD",
        Countries = new Dictionary<string, string>
        {
            ["BHS"] = "Commonwealth of the Bahamas",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Bahraini Dinar
    /// </summary>
    public static CurrencyInfo BahrainiDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "دينار بحريني",
        OfficialName = "Bahraini Dinar",
        Symbol = ".د.ب",
        NumericCode = "048",
        AlphabeticCode = "BHD",
        Countries = new Dictionary<string, string>
        {
            ["BHR"] = "Kingdom of Bahrain",
        },
        MinorUnit = 3,
    };

    /// <summary>
    /// Bangladeshi Taka
    /// </summary>
    public static CurrencyInfo BangladeshiTaka { get; } = new CurrencyInfo
    {
        CommonName = "Taka",
        NativeName = "বাংলাদেশী টাকা",
        OfficialName = "Bangladeshi Taka",
        Symbol = "৳",
        NumericCode = "050",
        AlphabeticCode = "BDT",
        Countries = new Dictionary<string, string>
        {
            ["BGD"] = "People's Republic of Bangladesh",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Barbadian Dollar
    /// </summary>
    public static CurrencyInfo BarbadianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Barbados Dollar",
        OfficialName = "Barbadian Dollar",
        Symbol = "$",
        NumericCode = "052",
        AlphabeticCode = "BBD",
        Countries = new Dictionary<string, string>
        {
            ["BRB"] = "Barbados",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Belarusian Ruble
    /// </summary>
    public static CurrencyInfo BelarusianRuble { get; } = new CurrencyInfo
    {
        CommonName = "Ruble",
        NativeName = "беларускі рубель",
        OfficialName = "Belarusian Ruble",
        Symbol = "Br",
        NumericCode = "933",
        AlphabeticCode = "BYN",
        Countries = new Dictionary<string, string>
        {
            ["BLR"] = "Republic of Belarus",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Belize Dollar
    /// </summary>
    public static CurrencyInfo BelizeDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Belize Dollar",
        OfficialName = "Belize Dollar",
        Symbol = "$",
        NumericCode = "084",
        AlphabeticCode = "BZD",
        Countries = new Dictionary<string, string>
        {
            ["BLZ"] = "Belize",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Bermudian Dollar
    /// </summary>
    public static CurrencyInfo BermudianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Bermuda Dollar",
        OfficialName = "Bermudian Dollar",
        Symbol = "$",
        NumericCode = "060",
        AlphabeticCode = "BMD",
        Countries = new Dictionary<string, string>
        {
            ["BMU"] = "Bermuda",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Bhutanese Ngultrum
    /// </summary>
    public static CurrencyInfo BhutaneseNgultrum { get; } = new CurrencyInfo
    {
        CommonName = "Ngultrum",
        NativeName = "འབྲུག་དངུལ་ཀྲམ",
        OfficialName = "Bhutanese Ngultrum",
        Symbol = "Nu.",
        NumericCode = "064",
        AlphabeticCode = "BTN",
        Countries = new Dictionary<string, string>
        {
            ["BTN"] = "Kingdom of Bhutan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Bolivian Boliviano
    /// </summary>
    public static CurrencyInfo BolivianBoliviano { get; } = new CurrencyInfo
    {
        CommonName = "Boliviano",
        NativeName = "Boliviano",
        OfficialName = "Bolivian Boliviano",
        Symbol = "Bs.",
        NumericCode = "068",
        AlphabeticCode = "BOB",
        Countries = new Dictionary<string, string>
        {
            ["BOL"] = "Plurinational State of Bolivia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Bosnia and Herzegovina Convertible Mark
    /// </summary>
    public static CurrencyInfo BosniaAndHerzegovinaConvertibleMark { get; } = new CurrencyInfo
    {
        CommonName = "Convertible mark",
        NativeName = "Bosanskohercegovački Konvertibilna Marka",
        OfficialName = "Bosnia and Herzegovina Convertible Mark",
        Symbol = "KM",
        NumericCode = "977",
        AlphabeticCode = "BAM",
        Countries = new Dictionary<string, string>
        {
            ["BIH"] = "Bosnia and Herzegovina",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Botswana Pula
    /// </summary>
    public static CurrencyInfo BotswanaPula { get; } = new CurrencyInfo
    {
        CommonName = "Pula",
        NativeName = "Pula ya Botswana",
        OfficialName = "Botswana Pula",
        Symbol = "P",
        NumericCode = "072",
        AlphabeticCode = "BWP",
        Countries = new Dictionary<string, string>
        {
            ["BWA"] = "Republic of Botswana",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Brazilian Real
    /// </summary>
    public static CurrencyInfo BrazilianReal { get; } = new CurrencyInfo
    {
        CommonName = "Real",
        NativeName = "Real Brasileiro",
        OfficialName = "Brazilian Real",
        Symbol = "R$",
        NumericCode = "986",
        AlphabeticCode = "BRL",
        Countries = new Dictionary<string, string>
        {
            ["BRA"] = "Federative Republic of Brazil",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Brunei Dollar
    /// </summary>
    public static CurrencyInfo BruneiDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Ringgit Brunei",
        OfficialName = "Brunei Dollar",
        Symbol = "$",
        NumericCode = "096",
        AlphabeticCode = "BND",
        Countries = new Dictionary<string, string>
        {
            ["BRN"] = "Nation of Brunei, Abode of Peace",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Burundian Franc
    /// </summary>
    public static CurrencyInfo BurundianFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Ifaranga Ry’Uburundi",
        OfficialName = "Burundian Franc",
        Symbol = "FBu",
        NumericCode = "108",
        AlphabeticCode = "BIF",
        Countries = new Dictionary<string, string>
        {
            ["BDI"] = "Republic of Burundi",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Cambodian Riel
    /// </summary>
    public static CurrencyInfo CambodianRiel { get; } = new CurrencyInfo
    {
        CommonName = "Riel",
        NativeName = "រៀលកម្ពុជា",
        OfficialName = "Cambodian Riel",
        Symbol = "៛",
        NumericCode = "116",
        AlphabeticCode = "KHR",
        Countries = new Dictionary<string, string>
        {
            ["KHM"] = "Kingdom of Cambodia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Canadian Dollar
    /// </summary>
    public static CurrencyInfo CanadianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Dollar Canadien",
        OfficialName = "Canadian Dollar",
        Symbol = "$",
        NumericCode = "124",
        AlphabeticCode = "CAD",
        Countries = new Dictionary<string, string>
        {
            ["CAN"] = "Canada",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Cape Verdean Escudo
    /// </summary>
    public static CurrencyInfo CapeVerdeanEscudo { get; } = new CurrencyInfo
    {
        CommonName = "Cabo Verde Escudo",
        NativeName = "Escudo Cabo-Verdiano",
        OfficialName = "Cape Verdean Escudo",
        Symbol = "Esc",
        NumericCode = "132",
        AlphabeticCode = "CVE",
        Countries = new Dictionary<string, string>
        {
            ["CPV"] = "Republic of Cabo Verde",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Caribbean Guilder
    /// </summary>
    public static CurrencyInfo CaribbeanGuilder { get; } = new CurrencyInfo
    {
        CommonName = "Guilder",
        NativeName = "Caribische Gulden",
        OfficialName = "Caribbean Guilder",
        Symbol = "Cg.",
        NumericCode = "532",
        AlphabeticCode = "XCG",
        Countries = new Dictionary<string, string>
        {
            ["CUW"] = "Country of Curaçao",
            ["SXM"] = "Sint Maarten",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Cayman Islands Dollar
    /// </summary>
    public static CurrencyInfo CaymanIslandsDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Cayman Islands Dollar",
        OfficialName = "Cayman Islands Dollar",
        Symbol = "$",
        NumericCode = "136",
        AlphabeticCode = "KYD",
        Countries = new Dictionary<string, string>
        {
            ["CYM"] = "Cayman Islands",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Central African CFA Franc
    /// </summary>
    public static CurrencyInfo CentralAfricanCFAFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc de la Communauté Financière Africaine",
        OfficialName = "Central African CFA Franc",
        Symbol = "FCFA",
        NumericCode = "950",
        AlphabeticCode = "XAF",
        Countries = new Dictionary<string, string>
        {
            ["CMR"] = "Republic of Cameroon",
            ["CAF"] = "Central African Republic",
            ["COG"] = "Republic of the Congo",
            ["TCD"] = "Republic of Chad",
            ["GNQ"] = "Republic of Equatorial Guinea",
            ["GAB"] = "Gabonese Republic",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// CFP Franc
    /// </summary>
    public static CurrencyInfo CFPFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc Pacifique",
        OfficialName = "CFP Franc",
        Symbol = "CFPF",
        NumericCode = "953",
        AlphabeticCode = "XPF",
        Countries = new Dictionary<string, string>
        {
            ["PYF"] = "French Polynesia",
            ["NCL"] = "New Caledonia",
            ["WLF"] = "Territory of the Wallis and Futuna Islands",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Chilean Peso
    /// </summary>
    public static CurrencyInfo ChileanPeso { get; } = new CurrencyInfo
    {
        CommonName = "Peso",
        NativeName = "Peso Chileno",
        OfficialName = "Chilean Peso",
        Symbol = "$",
        NumericCode = "152",
        AlphabeticCode = "CLP",
        Countries = new Dictionary<string, string>
        {
            ["CHL"] = "Republic of Chile",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Colombian Peso
    /// </summary>
    public static CurrencyInfo ColombianPeso { get; } = new CurrencyInfo
    {
        CommonName = "Peso",
        NativeName = "Peso Colombiano",
        OfficialName = "Colombian Peso",
        Symbol = "$",
        NumericCode = "170",
        AlphabeticCode = "COP",
        Countries = new Dictionary<string, string>
        {
            ["COL"] = "Republic of Colombia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Comorian Franc
    /// </summary>
    public static CurrencyInfo ComorianFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "فرنك قمري",
        OfficialName = "Comorian Franc",
        Symbol = "CF",
        NumericCode = "174",
        AlphabeticCode = "KMF",
        Countries = new Dictionary<string, string>
        {
            ["COM"] = "Union of the Comoros",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Congolese Franc
    /// </summary>
    public static CurrencyInfo CongoleseFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc Congolais",
        OfficialName = "Congolese Franc",
        Symbol = "FC",
        NumericCode = "976",
        AlphabeticCode = "CDF",
        Countries = new Dictionary<string, string>
        {
            ["COD"] = "Democratic Republic of the Congo",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Costa Rican Colón
    /// </summary>
    public static CurrencyInfo CostaRicanColón { get; } = new CurrencyInfo
    {
        CommonName = "Colón",
        NativeName = "Colón Costarricense",
        OfficialName = "Costa Rican Colón",
        Symbol = "₡",
        NumericCode = "188",
        AlphabeticCode = "CRC",
        Countries = new Dictionary<string, string>
        {
            ["CRI"] = "Republic of Costa Rica",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Cuban Peso
    /// </summary>
    public static CurrencyInfo CubanPeso { get; } = new CurrencyInfo
    {
        CommonName = "Peso",
        NativeName = "Peso Cubano",
        OfficialName = "Cuban Peso",
        Symbol = "$",
        NumericCode = "192",
        AlphabeticCode = "CUP",
        Countries = new Dictionary<string, string>
        {
            ["CUB"] = "Republic of Cuba",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Czech Koruna
    /// </summary>
    public static CurrencyInfo CzechKoruna { get; } = new CurrencyInfo
    {
        CommonName = "Koruna",
        NativeName = "Česká Koruna",
        OfficialName = "Czech Koruna",
        Symbol = "Kč",
        NumericCode = "203",
        AlphabeticCode = "CZK",
        Countries = new Dictionary<string, string>
        {
            ["CZE"] = "Czech Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Danish Krone
    /// </summary>
    public static CurrencyInfo DanishKrone { get; } = new CurrencyInfo
    {
        CommonName = "Krone",
        NativeName = "Dansk Krone",
        OfficialName = "Danish Krone",
        Symbol = "kr.",
        NumericCode = "208",
        AlphabeticCode = "DKK",
        Countries = new Dictionary<string, string>
        {
            ["DNK"] = "Kingdom of Denmark",
            ["FRO"] = "Faroe Islands",
            ["GRL"] = "Greenland",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Djiboutian Franc
    /// </summary>
    public static CurrencyInfo DjiboutianFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc Djiboutien",
        OfficialName = "Djiboutian Franc",
        Symbol = "Fdj",
        NumericCode = "262",
        AlphabeticCode = "DJF",
        Countries = new Dictionary<string, string>
        {
            ["DJI"] = "Republic of Djibouti",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Dominican Peso
    /// </summary>
    public static CurrencyInfo DominicanPeso { get; } = new CurrencyInfo
    {
        CommonName = "Peso",
        NativeName = "Peso Dominicano",
        OfficialName = "Dominican Peso",
        Symbol = "RD$",
        NumericCode = "214",
        AlphabeticCode = "DOP",
        Countries = new Dictionary<string, string>
        {
            ["DOM"] = "Dominican Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// East Caribbean Dollar
    /// </summary>
    public static CurrencyInfo EastCaribbeanDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "East Caribbean Dollar",
        OfficialName = "East Caribbean Dollar",
        Symbol = "$",
        NumericCode = "951",
        AlphabeticCode = "XCD",
        Countries = new Dictionary<string, string>
        {
            ["AIA"] = "Anguilla",
            ["ATG"] = "Antigua and Barbuda",
            ["DMA"] = "Commonwealth of Dominica",
            ["GRD"] = "Grenada",
            ["MSR"] = "Montserrat",
            ["KNA"] = "Federation of Saint Christopher and Nevis",
            ["LCA"] = "Saint Lucia",
            ["VCT"] = "Saint Vincent and the Grenadines",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Egyptian Pound
    /// </summary>
    public static CurrencyInfo EgyptianPound { get; } = new CurrencyInfo
    {
        CommonName = "Pound",
        NativeName = "جنيه مصرى",
        OfficialName = "Egyptian Pound",
        Symbol = "£",
        NumericCode = "818",
        AlphabeticCode = "EGP",
        Countries = new Dictionary<string, string>
        {
            ["EGY"] = "Arab Republic of Egypt",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Eritrean Nakfa
    /// </summary>
    public static CurrencyInfo EritreanNakfa { get; } = new CurrencyInfo
    {
        CommonName = "Nakfa",
        NativeName = "ኤርትራዊ ናቅፋ",
        OfficialName = "Eritrean Nakfa",
        Symbol = "Nfk",
        NumericCode = "232",
        AlphabeticCode = "ERN",
        Countries = new Dictionary<string, string>
        {
            ["ERI"] = "State of Eritrea",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Ethiopian Birr
    /// </summary>
    public static CurrencyInfo EthiopianBirr { get; } = new CurrencyInfo
    {
        CommonName = "Birr",
        NativeName = "የኢትዮጵያ ብር",
        OfficialName = "Ethiopian Birr",
        Symbol = "ብር",
        NumericCode = "230",
        AlphabeticCode = "ETB",
        Countries = new Dictionary<string, string>
        {
            ["ETH"] = "Federal Democratic Republic of Ethiopia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Euro
    /// </summary>
    public static CurrencyInfo Euro { get; } = new CurrencyInfo
    {
        CommonName = "Euro",
        NativeName = "Euro",
        OfficialName = "Euro",
        Symbol = "€",
        NumericCode = "978",
        AlphabeticCode = "EUR",
        Countries = new Dictionary<string, string>
        {
            ["ALA"] = "Åland Islands",
            ["AND"] = "Principality of Andorra",
            ["ATF"] = "Territory of the French Southern and Antarctic Lands",
            ["AUT"] = "Republic of Austria",
            ["BEL"] = "Kingdom of Belgium",
            ["BGR"] = "Republic of Bulgaria",
            ["BLM"] = "Collectivity of Saint Barthélemy",
            ["CYP"] = "Republic of Cyprus",
            ["DEU"] = "Federal Republic of Germany",
            ["ESP"] = "Kingdom of Spain",
            ["EST"] = "Republic of Estonia",
            ["FIN"] = "Republic of Finland",
            ["FRA"] = "French Republic",
            ["GLP"] = "Guadeloupe",
            ["GRC"] = "Hellenic Republic",
            ["GUF"] = "Guiana",
            ["HRV"] = "Republic of Croatia",
            ["IRL"] = "Republic of Ireland",
            ["ITA"] = "Italian Republic",
            ["LTU"] = "Republic of Lithuania",
            ["LUX"] = "Grand Duchy of Luxembourg",
            ["LVA"] = "Republic of Latvia",
            ["MAF"] = "Saint Martin",
            ["MCO"] = "Principality of Monaco",
            ["MLT"] = "Republic of Malta",
            ["MNE"] = "Montenegro",
            ["MTQ"] = "Martinique",
            ["MYT"] = "Department of Mayotte",
            ["NLD"] = "Kingdom of the Netherlands",
            ["PRT"] = "Portuguese Republic",
            ["REU"] = "Réunion Island",
            ["SMR"] = "Republic of San Marino",
            ["SPM"] = "Saint Pierre and Miquelon",
            ["SVK"] = "Slovak Republic",
            ["SVN"] = "Republic of Slovenia",
            ["UNK"] = "Republic of Kosovo",
            ["VAT"] = "Vatican City State",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Falkland Islands Pound
    /// </summary>
    public static CurrencyInfo FalklandIslandsPound { get; } = new CurrencyInfo
    {
        CommonName = "Pound",
        NativeName = "Falkland Islands Pound",
        OfficialName = "Falkland Islands Pound",
        Symbol = "£",
        NumericCode = "238",
        AlphabeticCode = "FKP",
        Countries = new Dictionary<string, string>
        {
            ["FLK"] = "Falkland Islands",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Fijian Dollar
    /// </summary>
    public static CurrencyInfo FijianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Dola ni Viti",
        OfficialName = "Fijian Dollar",
        Symbol = "$",
        NumericCode = "242",
        AlphabeticCode = "FJD",
        Countries = new Dictionary<string, string>
        {
            ["FJI"] = "Republic of Fiji",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Gambian Dalasi
    /// </summary>
    public static CurrencyInfo GambianDalasi { get; } = new CurrencyInfo
    {
        CommonName = "Dalasi",
        NativeName = "Gambian Dalasi",
        OfficialName = "Gambian Dalasi",
        Symbol = "D",
        NumericCode = "270",
        AlphabeticCode = "GMD",
        Countries = new Dictionary<string, string>
        {
            ["GMB"] = "Republic of the Gambia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Georgian Lari
    /// </summary>
    public static CurrencyInfo GeorgianLari { get; } = new CurrencyInfo
    {
        CommonName = "Lari",
        NativeName = "ქართული ლარი",
        OfficialName = "Georgian Lari",
        Symbol = "₾",
        NumericCode = "981",
        AlphabeticCode = "GEL",
        Countries = new Dictionary<string, string>
        {
            ["GEO"] = "Georgia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Ghanaian Cedi
    /// </summary>
    public static CurrencyInfo GhanaianCedi { get; } = new CurrencyInfo
    {
        CommonName = "Cedi",
        NativeName = "Ghanaian Cedi",
        OfficialName = "Ghanaian Cedi",
        Symbol = "₵",
        NumericCode = "936",
        AlphabeticCode = "GHS",
        Countries = new Dictionary<string, string>
        {
            ["GHA"] = "Republic of Ghana",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Gibraltar Pound
    /// </summary>
    public static CurrencyInfo GibraltarPound { get; } = new CurrencyInfo
    {
        CommonName = "Pound",
        NativeName = "Gibraltar Pound",
        OfficialName = "Gibraltar Pound",
        Symbol = "£",
        NumericCode = "292",
        AlphabeticCode = "GIP",
        Countries = new Dictionary<string, string>
        {
            ["GIB"] = "Gibraltar",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Guatemalan Quetzal
    /// </summary>
    public static CurrencyInfo GuatemalanQuetzal { get; } = new CurrencyInfo
    {
        CommonName = "Quetzal",
        NativeName = "Quetzal Guatemalteco",
        OfficialName = "Guatemalan Quetzal",
        Symbol = "Q",
        NumericCode = "320",
        AlphabeticCode = "GTQ",
        Countries = new Dictionary<string, string>
        {
            ["GTM"] = "Republic of Guatemala",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Guinean Franc
    /// </summary>
    public static CurrencyInfo GuineanFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc Guinéen",
        OfficialName = "Guinean Franc",
        Symbol = "FG",
        NumericCode = "324",
        AlphabeticCode = "GNF",
        Countries = new Dictionary<string, string>
        {
            ["GIN"] = "Republic of Guinea",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Guyanese Dollar
    /// </summary>
    public static CurrencyInfo GuyaneseDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Guyanese Dollar",
        OfficialName = "Guyanese Dollar",
        Symbol = "$",
        NumericCode = "328",
        AlphabeticCode = "GYD",
        Countries = new Dictionary<string, string>
        {
            ["GUY"] = "Co-operative Republic of Guyana",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Haitian Gourde
    /// </summary>
    public static CurrencyInfo HaitianGourde { get; } = new CurrencyInfo
    {
        CommonName = "Gourde",
        NativeName = "Gourde Haïtienne",
        OfficialName = "Haitian Gourde",
        Symbol = "G",
        NumericCode = "332",
        AlphabeticCode = "HTG",
        Countries = new Dictionary<string, string>
        {
            ["HTI"] = "Republic of Haiti",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Honduran Lempira
    /// </summary>
    public static CurrencyInfo HonduranLempira { get; } = new CurrencyInfo
    {
        CommonName = "Lempira",
        NativeName = "Lempira Hondureño",
        OfficialName = "Honduran Lempira",
        Symbol = "L",
        NumericCode = "340",
        AlphabeticCode = "HNL",
        Countries = new Dictionary<string, string>
        {
            ["HND"] = "Republic of Honduras",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Hong Kong Dollar
    /// </summary>
    public static CurrencyInfo HongKongDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "港元",
        OfficialName = "Hong Kong Dollar",
        Symbol = "$",
        NumericCode = "344",
        AlphabeticCode = "HKD",
        Countries = new Dictionary<string, string>
        {
            ["HKG"] = "Hong Kong Special Administrative Region of the People's Republic of China",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Hungarian Forint
    /// </summary>
    public static CurrencyInfo HungarianForint { get; } = new CurrencyInfo
    {
        CommonName = "Forint",
        NativeName = "Magyar Forint",
        OfficialName = "Hungarian Forint",
        Symbol = "Ft",
        NumericCode = "348",
        AlphabeticCode = "HUF",
        Countries = new Dictionary<string, string>
        {
            ["HUN"] = "Hungary",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Icelandic Króna
    /// </summary>
    public static CurrencyInfo IcelandicKróna { get; } = new CurrencyInfo
    {
        CommonName = "Króna",
        NativeName = "Íslensk Króna",
        OfficialName = "Icelandic Króna",
        Symbol = "kr",
        NumericCode = "352",
        AlphabeticCode = "ISK",
        Countries = new Dictionary<string, string>
        {
            ["ISL"] = "Iceland",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Indian Rupee
    /// </summary>
    public static CurrencyInfo IndianRupee { get; } = new CurrencyInfo
    {
        CommonName = "Rupee",
        NativeName = "भारतीय रुपया",
        OfficialName = "Indian Rupee",
        Symbol = "₹",
        NumericCode = "356",
        AlphabeticCode = "INR",
        Countries = new Dictionary<string, string>
        {
            ["IND"] = "Republic of India",
            ["BTN"] = "Kingdom of Bhutan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Indonesian Rupiah
    /// </summary>
    public static CurrencyInfo IndonesianRupiah { get; } = new CurrencyInfo
    {
        CommonName = "Rupiah",
        NativeName = "Indonesian Rupiah",
        OfficialName = "Indonesian Rupiah",
        Symbol = "Rp",
        NumericCode = "360",
        AlphabeticCode = "IDR",
        Countries = new Dictionary<string, string>
        {
            ["IDN"] = "Republic of Indonesia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Iranian Rial
    /// </summary>
    public static CurrencyInfo IranianRial { get; } = new CurrencyInfo
    {
        CommonName = "Rial",
        NativeName = "ریال ایران",
        OfficialName = "Iranian Rial",
        Symbol = "﷼",
        NumericCode = "364",
        AlphabeticCode = "IRR",
        Countries = new Dictionary<string, string>
        {
            ["IRN"] = "Islamic Republic of Iran",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Iraqi Dinar
    /// </summary>
    public static CurrencyInfo IraqiDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "الدينار العراقي",
        OfficialName = "Iraqi Dinar",
        Symbol = "د.ع",
        NumericCode = "368",
        AlphabeticCode = "IQD",
        Countries = new Dictionary<string, string>
        {
            ["IRQ"] = "Republic of Iraq",
        },
        MinorUnit = 3,
    };

    /// <summary>
    /// Israeli New Shekel
    /// </summary>
    public static CurrencyInfo IsraeliNewShekel { get; } = new CurrencyInfo
    {
        CommonName = "Shekel",
        NativeName = "שקל חדש",
        OfficialName = "Israeli New Shekel",
        Symbol = "₪",
        NumericCode = "376",
        AlphabeticCode = "ILS",
        Countries = new Dictionary<string, string>
        {
            ["ISR"] = "State of Israel",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Jamaican Dollar
    /// </summary>
    public static CurrencyInfo JamaicanDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Jumiekan Dala",
        OfficialName = "Jamaican Dollar",
        Symbol = "$",
        NumericCode = "388",
        AlphabeticCode = "JMD",
        Countries = new Dictionary<string, string>
        {
            ["JAM"] = "Jamaica",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Japanese Yen
    /// </summary>
    public static CurrencyInfo JapaneseYen { get; } = new CurrencyInfo
    {
        CommonName = "Yen",
        NativeName = "日本円",
        OfficialName = "Japanese Yen",
        Symbol = "¥",
        NumericCode = "392",
        AlphabeticCode = "JPY",
        Countries = new Dictionary<string, string>
        {
            ["JPN"] = "Japan",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Jordanian Dinar
    /// </summary>
    public static CurrencyInfo JordanianDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "دينار أردني",
        OfficialName = "Jordanian Dinar",
        Symbol = "د.أ",
        NumericCode = "400",
        AlphabeticCode = "JOD",
        Countries = new Dictionary<string, string>
        {
            ["JOR"] = "Hashemite Kingdom of Jordan",
        },
        MinorUnit = 3,
    };

    /// <summary>
    /// Kazakhstani Tenge
    /// </summary>
    public static CurrencyInfo KazakhstaniTenge { get; } = new CurrencyInfo
    {
        CommonName = "Tenge",
        NativeName = "Қазақстан теңгесі",
        OfficialName = "Kazakhstani Tenge",
        Symbol = "₸",
        NumericCode = "398",
        AlphabeticCode = "KZT",
        Countries = new Dictionary<string, string>
        {
            ["KAZ"] = "Republic of Kazakhstan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Kenyan Shilling
    /// </summary>
    public static CurrencyInfo KenyanShilling { get; } = new CurrencyInfo
    {
        CommonName = "Shilling",
        NativeName = "Shilingi ya Kenya",
        OfficialName = "Kenyan Shilling",
        Symbol = "KSh",
        NumericCode = "404",
        AlphabeticCode = "KES",
        Countries = new Dictionary<string, string>
        {
            ["KEN"] = "Republic of Kenya",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Kuwaiti Dinar
    /// </summary>
    public static CurrencyInfo KuwaitiDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "دينار كويتي",
        OfficialName = "Kuwaiti Dinar",
        Symbol = "د.ك",
        NumericCode = "414",
        AlphabeticCode = "KWD",
        Countries = new Dictionary<string, string>
        {
            ["KWT"] = "State of Kuwait",
        },
        MinorUnit = 3,
    };

    /// <summary>
    /// Kyrgyzstani Som
    /// </summary>
    public static CurrencyInfo KyrgyzstaniSom { get; } = new CurrencyInfo
    {
        CommonName = "Som",
        NativeName = "Кыргыз сому",
        OfficialName = "Kyrgyzstani Som",
        Symbol = "⃀",
        NumericCode = "417",
        AlphabeticCode = "KGS",
        Countries = new Dictionary<string, string>
        {
            ["KGZ"] = "Kyrgyz Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Lao Kip
    /// </summary>
    public static CurrencyInfo LaoKip { get; } = new CurrencyInfo
    {
        CommonName = "Kip",
        NativeName = "ເງີນກີບລາວ",
        OfficialName = "Lao Kip",
        Symbol = "₭",
        NumericCode = "418",
        AlphabeticCode = "LAK",
        Countries = new Dictionary<string, string>
        {
            ["LAO"] = "Lao People's Democratic Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Lebanese Pound
    /// </summary>
    public static CurrencyInfo LebanesePound { get; } = new CurrencyInfo
    {
        CommonName = "Lira",
        NativeName = "ليرة لبنانية",
        OfficialName = "Lebanese Pound",
        Symbol = "ل.ل",
        NumericCode = "422",
        AlphabeticCode = "LBP",
        Countries = new Dictionary<string, string>
        {
            ["LBN"] = "Lebanese Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Lesotho Loti
    /// </summary>
    public static CurrencyInfo LesothoLoti { get; } = new CurrencyInfo
    {
        CommonName = "Loti",
        NativeName = "Loti ya Lesotho",
        OfficialName = "Lesotho Loti",
        Symbol = "L",
        NumericCode = "426",
        AlphabeticCode = "LSL",
        Countries = new Dictionary<string, string>
        {
            ["LSO"] = "Kingdom of Lesotho",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Liberian Dollar
    /// </summary>
    public static CurrencyInfo LiberianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Liberian Dollar",
        OfficialName = "Liberian Dollar",
        Symbol = "$",
        NumericCode = "430",
        AlphabeticCode = "LRD",
        Countries = new Dictionary<string, string>
        {
            ["LBR"] = "Republic of Liberia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Libyan Dinar
    /// </summary>
    public static CurrencyInfo LibyanDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "دينار ليبي",
        OfficialName = "Libyan Dinar",
        Symbol = "ل.د",
        NumericCode = "434",
        AlphabeticCode = "LYD",
        Countries = new Dictionary<string, string>
        {
            ["LBY"] = "State of Libya",
        },
        MinorUnit = 3,
    };

    /// <summary>
    /// Macanese Pataca
    /// </summary>
    public static CurrencyInfo MacanesePataca { get; } = new CurrencyInfo
    {
        CommonName = "Pataca",
        NativeName = "澳門元",
        OfficialName = "Macanese Pataca",
        Symbol = "P",
        NumericCode = "446",
        AlphabeticCode = "MOP",
        Countries = new Dictionary<string, string>
        {
            ["MAC"] = "Macao Special Administrative Region of the People's Republic of China",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Macedonian Denar
    /// </summary>
    public static CurrencyInfo MacedonianDenar { get; } = new CurrencyInfo
    {
        CommonName = "Denar",
        NativeName = "Македонски денар",
        OfficialName = "Macedonian Denar",
        Symbol = "ден",
        NumericCode = "807",
        AlphabeticCode = "MKD",
        Countries = new Dictionary<string, string>
        {
            ["MKD"] = "Republic of North Macedonia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Malagasy Ariary
    /// </summary>
    public static CurrencyInfo MalagasyAriary { get; } = new CurrencyInfo
    {
        CommonName = "Ariary",
        NativeName = "Ariary Malgache",
        OfficialName = "Malagasy Ariary",
        Symbol = "Ar",
        NumericCode = "969",
        AlphabeticCode = "MGA",
        Countries = new Dictionary<string, string>
        {
            ["MDG"] = "Republic of Madagascar",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Malawian Kwacha
    /// </summary>
    public static CurrencyInfo MalawianKwacha { get; } = new CurrencyInfo
    {
        CommonName = "Kwacha",
        NativeName = "Malawi Kwacha",
        OfficialName = "Malawian Kwacha",
        Symbol = "MK",
        NumericCode = "454",
        AlphabeticCode = "MWK",
        Countries = new Dictionary<string, string>
        {
            ["MWI"] = "Republic of Malawi",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Malaysian Ringgit
    /// </summary>
    public static CurrencyInfo MalaysianRinggit { get; } = new CurrencyInfo
    {
        CommonName = "Ringgit",
        NativeName = "Ringgit Malaysia",
        OfficialName = "Malaysian Ringgit",
        Symbol = "RM",
        NumericCode = "458",
        AlphabeticCode = "MYR",
        Countries = new Dictionary<string, string>
        {
            ["MYS"] = "Malaysia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Maldivian Rufiyaa
    /// </summary>
    public static CurrencyInfo MaldivianRufiyaa { get; } = new CurrencyInfo
    {
        CommonName = "Rufiyaa",
        NativeName = "ދިވެހިރުފިޔާ",
        OfficialName = "Maldivian Rufiyaa",
        Symbol = ".ރ",
        NumericCode = "462",
        AlphabeticCode = "MVR",
        Countries = new Dictionary<string, string>
        {
            ["MDV"] = "Republic of the Maldives",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Mauritanian Ouguiya
    /// </summary>
    public static CurrencyInfo MauritanianOuguiya { get; } = new CurrencyInfo
    {
        CommonName = "Ouguiya",
        NativeName = "أوقية موريتانية",
        OfficialName = "Mauritanian Ouguiya",
        Symbol = "UM",
        NumericCode = "929",
        AlphabeticCode = "MRU",
        Countries = new Dictionary<string, string>
        {
            ["MRT"] = "Islamic Republic of Mauritania",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Mauritian Rupee
    /// </summary>
    public static CurrencyInfo MauritianRupee { get; } = new CurrencyInfo
    {
        CommonName = "Rupee",
        NativeName = "Roupi Morisien",
        OfficialName = "Mauritian Rupee",
        Symbol = "₨",
        NumericCode = "480",
        AlphabeticCode = "MUR",
        Countries = new Dictionary<string, string>
        {
            ["MUS"] = "Republic of Mauritius",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Mexican Peso
    /// </summary>
    public static CurrencyInfo MexicanPeso { get; } = new CurrencyInfo
    {
        CommonName = "Peso",
        NativeName = "Peso Mexicano",
        OfficialName = "Mexican Peso",
        Symbol = "$",
        NumericCode = "484",
        AlphabeticCode = "MXN",
        Countries = new Dictionary<string, string>
        {
            ["MEX"] = "United Mexican States",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Moldovan Leu
    /// </summary>
    public static CurrencyInfo MoldovanLeu { get; } = new CurrencyInfo
    {
        CommonName = "Leu",
        NativeName = "Leu Moldovenesc",
        OfficialName = "Moldovan Leu",
        Symbol = "L",
        NumericCode = "498",
        AlphabeticCode = "MDL",
        Countries = new Dictionary<string, string>
        {
            ["MDA"] = "Republic of Moldova",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Mongolian Tögrög
    /// </summary>
    public static CurrencyInfo MongolianTögrög { get; } = new CurrencyInfo
    {
        CommonName = "Tögrög",
        NativeName = "Монгол төгрөг",
        OfficialName = "Mongolian Tögrög",
        Symbol = "₮",
        NumericCode = "496",
        AlphabeticCode = "MNT",
        Countries = new Dictionary<string, string>
        {
            ["MNG"] = "Mongolia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Moroccan Dirham
    /// </summary>
    public static CurrencyInfo MoroccanDirham { get; } = new CurrencyInfo
    {
        CommonName = "Dirham",
        NativeName = "الدرهم المغربي",
        OfficialName = "Moroccan Dirham",
        Symbol = "د.م.",
        NumericCode = "504",
        AlphabeticCode = "MAD",
        Countries = new Dictionary<string, string>
        {
            ["MAR"] = "Kingdom of Morocco",
            ["ESH"] = "Sahrawi Arab Democratic Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Mozambican Metical
    /// </summary>
    public static CurrencyInfo MozambicanMetical { get; } = new CurrencyInfo
    {
        CommonName = "Metical",
        NativeName = "Metical Moçambicano",
        OfficialName = "Mozambican Metical",
        Symbol = "MT",
        NumericCode = "943",
        AlphabeticCode = "MZN",
        Countries = new Dictionary<string, string>
        {
            ["MOZ"] = "Republic of Mozambique",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Myanmar Kyat
    /// </summary>
    public static CurrencyInfo MyanmarKyat { get; } = new CurrencyInfo
    {
        CommonName = "Kyat",
        NativeName = "မြန်မာ ကျပ်",
        OfficialName = "Myanmar Kyat",
        Symbol = "K",
        NumericCode = "104",
        AlphabeticCode = "MMK",
        Countries = new Dictionary<string, string>
        {
            ["MMR"] = "Republic of the Union of Myanmar",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Namibian Dollar
    /// </summary>
    public static CurrencyInfo NamibianDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Namibian Dollar",
        OfficialName = "Namibian Dollar",
        Symbol = "$",
        NumericCode = "516",
        AlphabeticCode = "NAD",
        Countries = new Dictionary<string, string>
        {
            ["NAM"] = "Republic of Namibia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Nepalese Rupee
    /// </summary>
    public static CurrencyInfo NepaleseRupee { get; } = new CurrencyInfo
    {
        CommonName = "Rupee",
        NativeName = "नेपाली रुपैयाँ",
        OfficialName = "Nepalese Rupee",
        Symbol = "रु",
        NumericCode = "524",
        AlphabeticCode = "NPR",
        Countries = new Dictionary<string, string>
        {
            ["NPL"] = "Federal Democratic Republic of Nepal",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// New Taiwan Dollar
    /// </summary>
    public static CurrencyInfo NewTaiwanDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "新台幣",
        OfficialName = "New Taiwan Dollar",
        Symbol = "$",
        NumericCode = "901",
        AlphabeticCode = "TWD",
        Countries = new Dictionary<string, string>
        {
            ["TWN"] = "Republic of China (Taiwan)",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// New Zealand Dollar
    /// </summary>
    public static CurrencyInfo NewZealandDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Tāra o Aotearoa",
        OfficialName = "New Zealand Dollar",
        Symbol = "$",
        NumericCode = "554",
        AlphabeticCode = "NZD",
        Countries = new Dictionary<string, string>
        {
            ["NZL"] = "New Zealand",
            ["COK"] = "Cook Islands",
            ["NIU"] = "Niue",
            ["PCN"] = "Pitcairn Group of Islands",
            ["TKL"] = "Tokelau",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Nicaraguan Córdoba
    /// </summary>
    public static CurrencyInfo NicaraguanCórdoba { get; } = new CurrencyInfo
    {
        CommonName = "Córdoba",
        NativeName = "Córdoba Nicaragüense",
        OfficialName = "Nicaraguan Córdoba",
        Symbol = "C$",
        NumericCode = "558",
        AlphabeticCode = "NIO",
        Countries = new Dictionary<string, string>
        {
            ["NIC"] = "Republic of Nicaragua",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Nigerian Naira
    /// </summary>
    public static CurrencyInfo NigerianNaira { get; } = new CurrencyInfo
    {
        CommonName = "Naira",
        NativeName = "Nigerian Naira",
        OfficialName = "Nigerian Naira",
        Symbol = "₦",
        NumericCode = "566",
        AlphabeticCode = "NGN",
        Countries = new Dictionary<string, string>
        {
            ["NGA"] = "Federal Republic of Nigeria",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// North Korean Won
    /// </summary>
    public static CurrencyInfo NorthKoreanWon { get; } = new CurrencyInfo
    {
        CommonName = "Won",
        NativeName = "조선 원",
        OfficialName = "North Korean Won",
        Symbol = "₩",
        NumericCode = "408",
        AlphabeticCode = "KPW",
        Countries = new Dictionary<string, string>
        {
            ["PRK"] = "Democratic People's Republic of Korea",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Norwegian Krone
    /// </summary>
    public static CurrencyInfo NorwegianKrone { get; } = new CurrencyInfo
    {
        CommonName = "Krone",
        NativeName = "Norsk Krone",
        OfficialName = "Norwegian Krone",
        Symbol = "kr",
        NumericCode = "578",
        AlphabeticCode = "NOK",
        Countries = new Dictionary<string, string>
        {
            ["NOR"] = "Kingdom of Norway",
            ["SJM"] = "Svalbard og Jan Mayen",
            ["BVT"] = "Bouvet Island",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Omani Rial
    /// </summary>
    public static CurrencyInfo OmaniRial { get; } = new CurrencyInfo
    {
        CommonName = "Rial",
        NativeName = "ريال عماني",
        OfficialName = "Omani Rial",
        Symbol = "ر.ع",
        NumericCode = "512",
        AlphabeticCode = "OMR",
        Countries = new Dictionary<string, string>
        {
            ["OMN"] = "Sultanate of Oman",
        },
        MinorUnit = 3,
    };

    /// <summary>
    /// Pakistani Rupee
    /// </summary>
    public static CurrencyInfo PakistaniRupee { get; } = new CurrencyInfo
    {
        CommonName = "Rupee",
        NativeName = "پاکستانی روپیہ",
        OfficialName = "Pakistani Rupee",
        Symbol = "₨",
        NumericCode = "586",
        AlphabeticCode = "PKR",
        Countries = new Dictionary<string, string>
        {
            ["PAK"] = "Islamic Republic of Pakistan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Panamanian Balboa
    /// </summary>
    public static CurrencyInfo PanamanianBalboa { get; } = new CurrencyInfo
    {
        CommonName = "Balboa",
        NativeName = "Balboa Panameño",
        OfficialName = "Panamanian Balboa",
        Symbol = "B/.",
        NumericCode = "590",
        AlphabeticCode = "PAB",
        Countries = new Dictionary<string, string>
        {
            ["PAN"] = "Republic of Panama",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Papua New Guinean Kina
    /// </summary>
    public static CurrencyInfo PapuaNewGuineanKina { get; } = new CurrencyInfo
    {
        CommonName = "Kina",
        NativeName = "Papua New Guinean Kina",
        OfficialName = "Papua New Guinean Kina",
        Symbol = "K",
        NumericCode = "598",
        AlphabeticCode = "PGK",
        Countries = new Dictionary<string, string>
        {
            ["PNG"] = "Independent State of Papua New Guinea",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Paraguayan Guarani
    /// </summary>
    public static CurrencyInfo ParaguayanGuarani { get; } = new CurrencyInfo
    {
        CommonName = "Guarani",
        NativeName = "Guaraní Paraguayo",
        OfficialName = "Paraguayan Guarani",
        Symbol = "₲",
        NumericCode = "600",
        AlphabeticCode = "PYG",
        Countries = new Dictionary<string, string>
        {
            ["PRY"] = "Republic of Paraguay",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Peruvian Sol
    /// </summary>
    public static CurrencyInfo PeruvianSol { get; } = new CurrencyInfo
    {
        CommonName = "Sol",
        NativeName = "Sol Peruano",
        OfficialName = "Peruvian Sol",
        Symbol = "S/",
        NumericCode = "604",
        AlphabeticCode = "PEN",
        Countries = new Dictionary<string, string>
        {
            ["PER"] = "Republic of Peru",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Philippine Peso
    /// </summary>
    public static CurrencyInfo PhilippinePeso { get; } = new CurrencyInfo
    {
        CommonName = "Piso",
        NativeName = "Piso ng Pilipinas",
        OfficialName = "Philippine Peso",
        Symbol = "₱",
        NumericCode = "608",
        AlphabeticCode = "PHP",
        Countries = new Dictionary<string, string>
        {
            ["PHL"] = "Republic of the Philippines",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Polish Złoty
    /// </summary>
    public static CurrencyInfo PolishZłoty { get; } = new CurrencyInfo
    {
        CommonName = "Złoty",
        NativeName = "Polski Złoty",
        OfficialName = "Polish Złoty",
        Symbol = "zł",
        NumericCode = "985",
        AlphabeticCode = "PLN",
        Countries = new Dictionary<string, string>
        {
            ["POL"] = "Republic of Poland",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Pound Sterling
    /// </summary>
    public static CurrencyInfo PoundSterling { get; } = new CurrencyInfo
    {
        CommonName = "Sterling",
        NativeName = "British Pound",
        OfficialName = "Pound Sterling",
        Symbol = "£",
        NumericCode = "826",
        AlphabeticCode = "GBP",
        Countries = new Dictionary<string, string>
        {
            ["GBR"] = "United Kingdom of Great Britain and Northern Ireland",
            ["IMN"] = "Isle of Man",
            ["JEY"] = "Bailiwick of Jersey",
            ["GIB"] = "Gibraltar",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Qatari Riyal
    /// </summary>
    public static CurrencyInfo QatariRiyal { get; } = new CurrencyInfo
    {
        CommonName = "Riyal",
        NativeName = "ريال قطري",
        OfficialName = "Qatari Riyal",
        Symbol = "ر.ق",
        NumericCode = "634",
        AlphabeticCode = "QAR",
        Countries = new Dictionary<string, string>
        {
            ["QAT"] = "State of Qatar",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Renminbi
    /// </summary>
    public static CurrencyInfo Renminbi { get; } = new CurrencyInfo
    {
        CommonName = "Renminbi",
        NativeName = "人民币",
        OfficialName = "Renminbi",
        Symbol = "¥",
        NumericCode = "156",
        AlphabeticCode = "CNY",
        Countries = new Dictionary<string, string>
        {
            ["CHN"] = "People's Republic of China",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Romanian Leu
    /// </summary>
    public static CurrencyInfo RomanianLeu { get; } = new CurrencyInfo
    {
        CommonName = "Leu",
        NativeName = "Leu Românesc",
        OfficialName = "Romanian Leu",
        Symbol = "lei",
        NumericCode = "946",
        AlphabeticCode = "RON",
        Countries = new Dictionary<string, string>
        {
            ["ROU"] = "Romania",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Russian Ruble
    /// </summary>
    public static CurrencyInfo RussianRuble { get; } = new CurrencyInfo
    {
        CommonName = "Ruble",
        NativeName = "российский рубль",
        OfficialName = "Russian Ruble",
        Symbol = "₽",
        NumericCode = "643",
        AlphabeticCode = "RUB",
        Countries = new Dictionary<string, string>
        {
            ["RUS"] = "Russian Federation",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Rwandan Franc
    /// </summary>
    public static CurrencyInfo RwandanFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc Rwandais",
        OfficialName = "Rwandan Franc",
        Symbol = "FRw",
        NumericCode = "646",
        AlphabeticCode = "RWF",
        Countries = new Dictionary<string, string>
        {
            ["RWA"] = "Republic of Rwanda",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Saint Helena Pound
    /// </summary>
    public static CurrencyInfo SaintHelenaPound { get; } = new CurrencyInfo
    {
        CommonName = "Pound",
        NativeName = "Saint Helena Pound",
        OfficialName = "Saint Helena Pound",
        Symbol = "£",
        NumericCode = "654",
        AlphabeticCode = "SHP",
        Countries = new Dictionary<string, string>
        {
            ["SHN"] = "Saint Helena, Ascension and Tristan da Cunha",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Salvadoran Colón
    /// </summary>
    public static CurrencyInfo SalvadoranColón { get; } = new CurrencyInfo
    {
        CommonName = "Colón",
        NativeName = "Colón Salvadoreño",
        OfficialName = "Salvadoran Colón",
        Symbol = "₡",
        NumericCode = "222",
        AlphabeticCode = "SVC",
        Countries = new Dictionary<string, string>
        {
            ["SLV"] = "Republic of El Salvador",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Samoan Tālā
    /// </summary>
    public static CurrencyInfo SamoanTālā { get; } = new CurrencyInfo
    {
        CommonName = "Tālā",
        NativeName = "Sāmoa Tālā",
        OfficialName = "Samoan Tālā",
        Symbol = "T",
        NumericCode = "882",
        AlphabeticCode = "WST",
        Countries = new Dictionary<string, string>
        {
            ["WSM"] = "Independent State of Samoa",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// São Tomé and Príncipe Dobra
    /// </summary>
    public static CurrencyInfo SãoToméAndPríncipeDobra { get; } = new CurrencyInfo
    {
        CommonName = "Dobra",
        NativeName = "Dobra São-Tomense",
        OfficialName = "São Tomé and Príncipe Dobra",
        Symbol = "Db",
        NumericCode = "930",
        AlphabeticCode = "STN",
        Countries = new Dictionary<string, string>
        {
            ["STP"] = "Democratic Republic of São Tomé and Príncipe",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Saudi Riyal
    /// </summary>
    public static CurrencyInfo SaudiRiyal { get; } = new CurrencyInfo
    {
        CommonName = "Riyal",
        NativeName = "ريال سعودي",
        OfficialName = "Saudi Riyal",
        Symbol = "ر.س",
        NumericCode = "682",
        AlphabeticCode = "SAR",
        Countries = new Dictionary<string, string>
        {
            ["SAU"] = "Kingdom of Saudi Arabia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Serbian Dinar
    /// </summary>
    public static CurrencyInfo SerbianDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "српски динар",
        OfficialName = "Serbian Dinar",
        Symbol = "дин.",
        NumericCode = "941",
        AlphabeticCode = "RSD",
        Countries = new Dictionary<string, string>
        {
            ["SRB"] = "Republic of Serbia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Seychellois Rupee
    /// </summary>
    public static CurrencyInfo SeychelloisRupee { get; } = new CurrencyInfo
    {
        CommonName = "Rupee",
        NativeName = "Roupie Seychelloise",
        OfficialName = "Seychellois Rupee",
        Symbol = "₨",
        NumericCode = "690",
        AlphabeticCode = "SCR",
        Countries = new Dictionary<string, string>
        {
            ["SYC"] = "Republic of Seychelles",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Sierra Leonean Leone
    /// </summary>
    public static CurrencyInfo SierraLeoneanLeone { get; } = new CurrencyInfo
    {
        CommonName = "Leone",
        NativeName = "Sierra Leonean Leone",
        OfficialName = "Sierra Leonean Leone",
        Symbol = "Le",
        NumericCode = "925",
        AlphabeticCode = "SLE",
        Countries = new Dictionary<string, string>
        {
            ["SLE"] = "Republic of Sierra Leone",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Singapore Dollar
    /// </summary>
    public static CurrencyInfo SingaporeDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "新加坡元",
        OfficialName = "Singapore Dollar",
        Symbol = "$",
        NumericCode = "702",
        AlphabeticCode = "SGD",
        Countries = new Dictionary<string, string>
        {
            ["SGP"] = "Republic of Singapore",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Solomon Islands Dollar
    /// </summary>
    public static CurrencyInfo SolomonIslandsDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Solomon Islands Dollar",
        OfficialName = "Solomon Islands Dollar",
        Symbol = "$",
        NumericCode = "090",
        AlphabeticCode = "SBD",
        Countries = new Dictionary<string, string>
        {
            ["SLB"] = "Solomon Islands",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Somali Shilling
    /// </summary>
    public static CurrencyInfo SomaliShilling { get; } = new CurrencyInfo
    {
        CommonName = "Shilling",
        NativeName = "Shilin Soomaali",
        OfficialName = "Somali Shilling",
        Symbol = "Sh.So.",
        NumericCode = "706",
        AlphabeticCode = "SOS",
        Countries = new Dictionary<string, string>
        {
            ["SOM"] = "Federal Republic of Somalia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// South African Rand
    /// </summary>
    public static CurrencyInfo SouthAfricanRand { get; } = new CurrencyInfo
    {
        CommonName = "Rand",
        NativeName = "Suid-Afrikaanse Rand",
        OfficialName = "South African Rand",
        Symbol = "R",
        NumericCode = "710",
        AlphabeticCode = "ZAR",
        Countries = new Dictionary<string, string>
        {
            ["ZAF"] = "Republic of South Africa",
            ["SWZ"] = "Kingdom of Eswatini",
            ["LSO"] = "Kingdom of Lesotho",
            ["NAM"] = "Republic of Namibia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// South Korean Won
    /// </summary>
    public static CurrencyInfo SouthKoreanWon { get; } = new CurrencyInfo
    {
        CommonName = "Won",
        NativeName = "대한민국 원",
        OfficialName = "South Korean Won",
        Symbol = "₩",
        NumericCode = "410",
        AlphabeticCode = "KRW",
        Countries = new Dictionary<string, string>
        {
            ["KOR"] = "Republic of Korea",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// South Sudanese Pound
    /// </summary>
    public static CurrencyInfo SouthSudanesePound { get; } = new CurrencyInfo
    {
        CommonName = "Pound",
        NativeName = "South Sudanese Pound",
        OfficialName = "South Sudanese Pound",
        Symbol = "£",
        NumericCode = "728",
        AlphabeticCode = "SSP",
        Countries = new Dictionary<string, string>
        {
            ["SSD"] = "Republic of South Sudan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Sri Lankan Rupee
    /// </summary>
    public static CurrencyInfo SriLankanRupee { get; } = new CurrencyInfo
    {
        CommonName = "Rupee",
        NativeName = "ශ්‍රී ලංකා රුපියල්",
        OfficialName = "Sri Lankan Rupee",
        Symbol = "රු",
        NumericCode = "144",
        AlphabeticCode = "LKR",
        Countries = new Dictionary<string, string>
        {
            ["LKA"] = "Democratic Socialist Republic of Sri Lanka",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Sudanese Pound
    /// </summary>
    public static CurrencyInfo SudanesePound { get; } = new CurrencyInfo
    {
        CommonName = "Pound",
        NativeName = "جنيه سوداني",
        OfficialName = "Sudanese Pound",
        Symbol = "ج.س",
        NumericCode = "938",
        AlphabeticCode = "SDG",
        Countries = new Dictionary<string, string>
        {
            ["SDN"] = "Republic of the Sudan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Surinamese Dollar
    /// </summary>
    public static CurrencyInfo SurinameseDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Surinaamse Dollar",
        OfficialName = "Surinamese Dollar",
        Symbol = "$",
        NumericCode = "968",
        AlphabeticCode = "SRD",
        Countries = new Dictionary<string, string>
        {
            ["SUR"] = "Republic of Suriname",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Swazi Lilangeni
    /// </summary>
    public static CurrencyInfo SwaziLilangeni { get; } = new CurrencyInfo
    {
        CommonName = "Lilangeni",
        NativeName = "Swazi Lilangeni",
        OfficialName = "Swazi Lilangeni",
        Symbol = "L",
        NumericCode = "748",
        AlphabeticCode = "SZL",
        Countries = new Dictionary<string, string>
        {
            ["SWZ"] = "Kingdom of Eswatini",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Swedish Krona
    /// </summary>
    public static CurrencyInfo SwedishKrona { get; } = new CurrencyInfo
    {
        CommonName = "Krona",
        NativeName = "Svensk Krona",
        OfficialName = "Swedish Krona",
        Symbol = "kr",
        NumericCode = "752",
        AlphabeticCode = "SEK",
        Countries = new Dictionary<string, string>
        {
            ["SWE"] = "Kingdom of Sweden",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Swiss Franc
    /// </summary>
    public static CurrencyInfo SwissFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc Suisse",
        OfficialName = "Swiss Franc",
        Symbol = "CHF",
        NumericCode = "756",
        AlphabeticCode = "CHF",
        Countries = new Dictionary<string, string>
        {
            ["CHE"] = "Swiss Confederation",
            ["LIE"] = "Principality of Liechtenstein",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Syrian Pound
    /// </summary>
    public static CurrencyInfo SyrianPound { get; } = new CurrencyInfo
    {
        CommonName = "Pound",
        NativeName = "الليرة السورية",
        OfficialName = "Syrian Pound",
        Symbol = "ل.س",
        NumericCode = "760",
        AlphabeticCode = "SYP",
        Countries = new Dictionary<string, string>
        {
            ["SYR"] = "Syrian Arab Republic",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Tajikistani Somoni
    /// </summary>
    public static CurrencyInfo TajikistaniSomoni { get; } = new CurrencyInfo
    {
        CommonName = "Somoni",
        NativeName = "сомонӣ тоҷикӣ",
        OfficialName = "Tajikistani Somoni",
        Symbol = "ЅМ",
        NumericCode = "972",
        AlphabeticCode = "TJS",
        Countries = new Dictionary<string, string>
        {
            ["TJK"] = "Republic of Tajikistan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Tanzanian Shilling
    /// </summary>
    public static CurrencyInfo TanzanianShilling { get; } = new CurrencyInfo
    {
        CommonName = "Shilling",
        NativeName = "Shilingi za Kitanzania",
        OfficialName = "Tanzanian Shilling",
        Symbol = "TSh",
        NumericCode = "834",
        AlphabeticCode = "TZS",
        Countries = new Dictionary<string, string>
        {
            ["TZA"] = "United Republic of Tanzania",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Thai Baht
    /// </summary>
    public static CurrencyInfo ThaiBaht { get; } = new CurrencyInfo
    {
        CommonName = "Baht",
        NativeName = "บาทไทย",
        OfficialName = "Thai Baht",
        Symbol = "฿",
        NumericCode = "764",
        AlphabeticCode = "THB",
        Countries = new Dictionary<string, string>
        {
            ["THA"] = "Kingdom of Thailand",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Tongan Paʻanga
    /// </summary>
    public static CurrencyInfo TonganPaanga { get; } = new CurrencyInfo
    {
        CommonName = "Pa'anga",
        NativeName = "Paʻanga Fakatonga",
        OfficialName = "Tongan Paʻanga",
        Symbol = "T$",
        NumericCode = "776",
        AlphabeticCode = "TOP",
        Countries = new Dictionary<string, string>
        {
            ["TON"] = "Kingdom of Tonga",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Trinidad and Tobago Dollar
    /// </summary>
    public static CurrencyInfo TrinidadAndTobagoDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "Trinidad and Tobago Dollar",
        OfficialName = "Trinidad and Tobago Dollar",
        Symbol = "$",
        NumericCode = "780",
        AlphabeticCode = "TTD",
        Countries = new Dictionary<string, string>
        {
            ["TTO"] = "Republic of Trinidad and Tobago",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Tunisian Dinar
    /// </summary>
    public static CurrencyInfo TunisianDinar { get; } = new CurrencyInfo
    {
        CommonName = "Dinar",
        NativeName = "دينار تونسي",
        OfficialName = "Tunisian Dinar",
        Symbol = "د.ت",
        NumericCode = "788",
        AlphabeticCode = "TND",
        Countries = new Dictionary<string, string>
        {
            ["TUN"] = "Tunisian Republic",
        },
        MinorUnit = 3,
    };

    /// <summary>
    /// Turkish Lira
    /// </summary>
    public static CurrencyInfo TurkishLira { get; } = new CurrencyInfo
    {
        CommonName = "Lira",
        NativeName = "Türk Lirası",
        OfficialName = "Turkish Lira",
        Symbol = "₺",
        NumericCode = "949",
        AlphabeticCode = "TRY",
        Countries = new Dictionary<string, string>
        {
            ["TUR"] = "Republic of Turkey",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Turkmenistan Manat
    /// </summary>
    public static CurrencyInfo TurkmenistanManat { get; } = new CurrencyInfo
    {
        CommonName = "Manat",
        NativeName = "Türkmen Manady",
        OfficialName = "Turkmenistan Manat",
        Symbol = "m",
        NumericCode = "934",
        AlphabeticCode = "TMT",
        Countries = new Dictionary<string, string>
        {
            ["TKM"] = "Turkmenistan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Ugandan Shilling
    /// </summary>
    public static CurrencyInfo UgandanShilling { get; } = new CurrencyInfo
    {
        CommonName = "Shilling",
        NativeName = "Shilingi ya Uganda",
        OfficialName = "Ugandan Shilling",
        Symbol = "USh",
        NumericCode = "800",
        AlphabeticCode = "UGX",
        Countries = new Dictionary<string, string>
        {
            ["UGA"] = "Republic of Uganda",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Ukrainian Hryvnia
    /// </summary>
    public static CurrencyInfo UkrainianHryvnia { get; } = new CurrencyInfo
    {
        CommonName = "Hryvnia",
        NativeName = "українська гривня",
        OfficialName = "Ukrainian Hryvnia",
        Symbol = "₴",
        NumericCode = "980",
        AlphabeticCode = "UAH",
        Countries = new Dictionary<string, string>
        {
            ["UKR"] = "Ukraine",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// United Arab Emirates Dirham
    /// </summary>
    public static CurrencyInfo UnitedArabEmiratesDirham { get; } = new CurrencyInfo
    {
        CommonName = "Dirham",
        NativeName = "درهم إماراتي",
        OfficialName = "United Arab Emirates Dirham",
        Symbol = "د.إ",
        NumericCode = "784",
        AlphabeticCode = "AED",
        Countries = new Dictionary<string, string>
        {
            ["ARE"] = "United Arab Emirates",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// United States Dollar
    /// </summary>
    public static CurrencyInfo UnitedStatesDollar { get; } = new CurrencyInfo
    {
        CommonName = "Dollar",
        NativeName = "United States Dollar",
        OfficialName = "United States Dollar",
        Symbol = "$",
        NumericCode = "840",
        AlphabeticCode = "USD",
        Countries = new Dictionary<string, string>
        {
            ["USA"] = "United States of America",
            ["ASM"] = "American Samoa",
            ["IOT"] = "British Indian Ocean Territory",
            ["VGB"] = "Virgin Islands",
            ["BES"] = "Bonaire, Sint Eustatius and Saba",
            ["ECU"] = "Republic of Ecuador",
            ["SLV"] = "Republic of El Salvador",
            ["GUM"] = "Guam",
            ["MHL"] = "Republic of the Marshall Islands",
            ["FSM"] = "Federated States of Micronesia",
            ["MNP"] = "Commonwealth of the Northern Mariana Islands",
            ["PLW"] = "Republic of Palau",
            ["PAN"] = "Republic of Panama",
            ["PRI"] = "Commonwealth of Puerto Rico",
            ["TLS"] = "Democratic Republic of Timor-Leste",
            ["TCA"] = "Turks and Caicos Islands",
            ["VIR"] = "Virgin Islands of the United States",
            ["UMI"] = "United States Minor Outlying Islands",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Uruguayan Peso
    /// </summary>
    public static CurrencyInfo UruguayanPeso { get; } = new CurrencyInfo
    {
        CommonName = "Peso",
        NativeName = "Peso Uruguayo",
        OfficialName = "Uruguayan Peso",
        Symbol = "$U",
        NumericCode = "858",
        AlphabeticCode = "UYU",
        Countries = new Dictionary<string, string>
        {
            ["URY"] = "Oriental Republic of Uruguay",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Uzbekistani Soʻm
    /// </summary>
    public static CurrencyInfo UzbekistaniSom { get; } = new CurrencyInfo
    {
        CommonName = "Soʻm",
        NativeName = "Ўзбек сўми",
        OfficialName = "Uzbekistani Soʻm",
        Symbol = "soʻm",
        NumericCode = "860",
        AlphabeticCode = "UZS",
        Countries = new Dictionary<string, string>
        {
            ["UZB"] = "Republic of Uzbekistan",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Vanuatu Vatu
    /// </summary>
    public static CurrencyInfo VanuatuVatu { get; } = new CurrencyInfo
    {
        CommonName = "Vatu",
        NativeName = "vatu Vanuatuan",
        OfficialName = "Vanuatu Vatu",
        Symbol = "VT",
        NumericCode = "548",
        AlphabeticCode = "VUV",
        Countries = new Dictionary<string, string>
        {
            ["VUT"] = "Republic of Vanuatu",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Venezuelan Digital Bolívar
    /// </summary>
    public static CurrencyInfo VenezuelanDigitalBolívar { get; } = new CurrencyInfo
    {
        CommonName = "Bolívar",
        NativeName = "Bolívar Soberano",
        OfficialName = "Venezuelan Digital Bolívar",
        Symbol = "Bs.D",
        NumericCode = "926",
        AlphabeticCode = "VED",
        Countries = new Dictionary<string, string>
        {
            ["VEN"] = "Bolivarian Republic of Venezuela",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Venezuelan Sovereign Bolívar
    /// </summary>
    public static CurrencyInfo VenezuelanSovereignBolívar { get; } = new CurrencyInfo
    {
        CommonName = "Bolívar",
        NativeName = "Bolívar Soberano",
        OfficialName = "Venezuelan Sovereign Bolívar",
        Symbol = "Bs.S",
        NumericCode = "928",
        AlphabeticCode = "VES",
        Countries = new Dictionary<string, string>
        {
            ["VEN"] = "Bolivarian Republic of Venezuela",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Vietnamese Đồng
    /// </summary>
    public static CurrencyInfo VietnameseĐồng { get; } = new CurrencyInfo
    {
        CommonName = "Dong",
        NativeName = "Đồng Việt Nam",
        OfficialName = "Vietnamese Đồng",
        Symbol = "₫",
        NumericCode = "704",
        AlphabeticCode = "VND",
        Countries = new Dictionary<string, string>
        {
            ["VNM"] = "Socialist Republic of Vietnam",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// West African CFA Franc
    /// </summary>
    public static CurrencyInfo WestAfricanCFAFranc { get; } = new CurrencyInfo
    {
        CommonName = "Franc",
        NativeName = "Franc de la Communauté Financière Africaine",
        OfficialName = "West African CFA Franc",
        Symbol = "CFA",
        NumericCode = "952",
        AlphabeticCode = "XOF",
        Countries = new Dictionary<string, string>
        {
            ["BEN"] = "Republic of Benin",
            ["BFA"] = "Burkina Faso",
            ["CIV"] = "Republic of Côte d'Ivoire",
            ["GMB"] = "Republic of the Gambia",
            ["MLI"] = "Republic of Mali",
            ["NER"] = "Republic of Niger",
            ["SEN"] = "Republic of Senegal",
            ["TGO"] = "Togolese Republic",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// Yemeni Rial
    /// </summary>
    public static CurrencyInfo YemeniRial { get; } = new CurrencyInfo
    {
        CommonName = "Rial",
        NativeName = "ريال يمني",
        OfficialName = "Yemeni Rial",
        Symbol = "﷼",
        NumericCode = "886",
        AlphabeticCode = "YER",
        Countries = new Dictionary<string, string>
        {
            ["YEM"] = "Republic of Yemen",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Zambian Kwacha
    /// </summary>
    public static CurrencyInfo ZambianKwacha { get; } = new CurrencyInfo
    {
        CommonName = "Kwacha",
        NativeName = "Zambian Kwacha",
        OfficialName = "Zambian Kwacha",
        Symbol = "K",
        NumericCode = "967",
        AlphabeticCode = "ZMW",
        Countries = new Dictionary<string, string>
        {
            ["ZMB"] = "Republic of Zambia",
        },
        MinorUnit = 2,
    };
}
