// <auto-generated>
//     This file was automatically generated on 15 January 2026 at 20:26:57 UTC.
//     Any manual changes may cause errors and will be overwritten when regenerated.
// </auto-generated>

#pragma warning disable IDE0130
namespace Firell.Standards;
#pragma warning restore IDE0130

public partial record CurrencyInfo
{
    /// <summary>
    /// ABD Unit of Account
    /// </summary>
    /// <remarks>
    /// African Development Bank
    /// </remarks>
    public static CurrencyInfo ABDUnitOfAccount { get; } = new CurrencyInfo
    {
        CommonName = "ABD Unit of Account",
        NativeName = "ABD Unit of Account",
        OfficialName = "ABD Unit of Account",
        Symbol = null,
        NumericCode = "965",
        AlphabeticCode = "XUA",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Arab Accounting Dinar
    /// </summary>
    /// <remarks>
    /// Arab Monetary Fund
    /// </remarks>
    public static CurrencyInfo ArabAccountingDinar { get; } = new CurrencyInfo
    {
        CommonName = "Arab Accounting Dinar",
        NativeName = "Arab Accounting Dinar",
        OfficialName = "Arab Accounting Dinar",
        Symbol = null,
        NumericCode = "396",
        AlphabeticCode = "XAD",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Bolivian Mvdol
    /// </summary>
    /// <remarks>
    /// Bolivian Monetary Authority
    /// </remarks>
    public static CurrencyInfo BolivianMvdol { get; } = new CurrencyInfo
    {
        CommonName = "Bolivian Mvdol",
        NativeName = "Bolivian Mvdol",
        OfficialName = "Bolivian Mvdol",
        Symbol = null,
        NumericCode = "984",
        AlphabeticCode = "BOV",
        Countries = new Dictionary<string, string>
        {
            ["BOL"] = "Plurinational State of Bolivia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// European Composite Unit (EURCO)
    /// </summary>
    /// <remarks>
    /// European Communities
    /// </remarks>
    public static CurrencyInfo EuropeanCompositeUnit { get; } = new CurrencyInfo
    {
        CommonName = "European Composite Unit (EURCO)",
        NativeName = "European Composite Unit (EURCO)",
        OfficialName = "European Composite Unit (EURCO)",
        Symbol = null,
        NumericCode = "955",
        AlphabeticCode = "XBA",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// European Monetary Unit (E.M.U.-6)
    /// </summary>
    /// <remarks>
    /// European Communities
    /// </remarks>
    public static CurrencyInfo EuropeanMonetaryUnit { get; } = new CurrencyInfo
    {
        CommonName = "European Monetary Unit (E.M.U.-6)",
        NativeName = "European Monetary Unit (E.M.U.-6)",
        OfficialName = "European Monetary Unit (E.M.U.-6)",
        Symbol = null,
        NumericCode = "956",
        AlphabeticCode = "XBB",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// European Unit of Account 17 (E.U.A.-17)
    /// </summary>
    /// <remarks>
    /// European Communities
    /// </remarks>
    public static CurrencyInfo EuropeanUnitOfAccount17 { get; } = new CurrencyInfo
    {
        CommonName = "European Unit of Account 17 (E.U.A.-17)",
        NativeName = "European Unit of Account 17 (E.U.A.-17)",
        OfficialName = "European Unit of Account 17 (E.U.A.-17)",
        Symbol = null,
        NumericCode = "958",
        AlphabeticCode = "XBD",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// European Unit of Account 9 (E.U.A.-9)
    /// </summary>
    /// <remarks>
    /// European Communities
    /// </remarks>
    public static CurrencyInfo EuropeanUnitOfAccount9 { get; } = new CurrencyInfo
    {
        CommonName = "European Unit of Account 9 (E.U.A.-9)",
        NativeName = "European Unit of Account 9 (E.U.A.-9)",
        OfficialName = "European Unit of Account 9 (E.U.A.-9)",
        Symbol = null,
        NumericCode = "957",
        AlphabeticCode = "XBC",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Mexican Unidad de Inversion (UDI)
    /// </summary>
    public static CurrencyInfo MexicanUnidadDeInversion { get; } = new CurrencyInfo
    {
        CommonName = "Mexican Unidad de Inversion (UDI)",
        NativeName = "Mexican Unidad de Inversion (UDI)",
        OfficialName = "Mexican Unidad de Inversion (UDI)",
        Symbol = null,
        NumericCode = "979",
        AlphabeticCode = "MXV",
        Countries = new Dictionary<string, string>
        {
            ["MEX"] = "United Mexican States",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// No Currency
    /// </summary>
    /// <remarks>
    /// Used for transactions where no currency is involved
    /// </remarks>
    public static CurrencyInfo NoCurrency { get; } = new CurrencyInfo
    {
        CommonName = "No Currency",
        NativeName = "No Currency",
        OfficialName = "No Currency",
        Symbol = null,
        NumericCode = "999",
        AlphabeticCode = "XXX",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Special Drawing Rights
    /// </summary>
    /// <remarks>
    /// International Monetary Fund
    /// </remarks>
    public static CurrencyInfo SpecialDrawingRights { get; } = new CurrencyInfo
    {
        CommonName = "Special Drawing Rights",
        NativeName = "Special Drawing Rights",
        OfficialName = "Special Drawing Rights",
        Symbol = null,
        NumericCode = "960",
        AlphabeticCode = "XDR",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// SUCRE
    /// </summary>
    /// <remarks>
    /// Unified System for Regional Compensation
    /// </remarks>
    public static CurrencyInfo SUCRE { get; } = new CurrencyInfo
    {
        CommonName = "SUCRE",
        NativeName = "SUCRE",
        OfficialName = "SUCRE",
        Symbol = null,
        NumericCode = "994",
        AlphabeticCode = "XSU",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Test Currency
    /// </summary>
    /// <remarks>
    /// Code reserved for testing purposes
    /// </remarks>
    public static CurrencyInfo TestCurrency { get; } = new CurrencyInfo
    {
        CommonName = "Test Currency",
        NativeName = "Test Currency",
        OfficialName = "Test Currency",
        Symbol = null,
        NumericCode = "963",
        AlphabeticCode = "XTS",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = null,
    };

    /// <summary>
    /// Unidad de Fomento (UF)
    /// </summary>
    public static CurrencyInfo UnidadDeFomento { get; } = new CurrencyInfo
    {
        CommonName = "Unidad de Fomento (UF)",
        NativeName = "Unidad de Fomento (UF)",
        OfficialName = "Unidad de Fomento (UF)",
        Symbol = null,
        NumericCode = "990",
        AlphabeticCode = "CLF",
        Countries = new Dictionary<string, string>
        {
            ["CHL"] = "Republic of Chile",
        },
        MinorUnit = 4,
    };

    /// <summary>
    /// Unidad de Valor Real (UVR)
    /// </summary>
    public static CurrencyInfo UnidadDeValorReal { get; } = new CurrencyInfo
    {
        CommonName = "Unidad de Valor Real (UVR)",
        NativeName = "Unidad de Valor Real (UVR)",
        OfficialName = "Unidad de Valor Real (UVR)",
        Symbol = null,
        NumericCode = "970",
        AlphabeticCode = "COU",
        Countries = new Dictionary<string, string>
        {
            ["COL"] = "Republic of Colombia",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Unidad Previsional
    /// </summary>
    public static CurrencyInfo UnidadPrevisional { get; } = new CurrencyInfo
    {
        CommonName = "Unidad Previsional",
        NativeName = "Unidad Previsional",
        OfficialName = "Unidad Previsional",
        Symbol = null,
        NumericCode = "927",
        AlphabeticCode = "UYW",
        Countries = new Dictionary<string, string>
        {
            ["URY"] = "Oriental Republic of Uruguay",
        },
        MinorUnit = 4,
    };

    /// <summary>
    /// United States Dollar (Next Day)
    /// </summary>
    public static CurrencyInfo UnitedStatesDollarNextDay { get; } = new CurrencyInfo
    {
        CommonName = "United States Dollar (Next Day)",
        NativeName = "United States Dollar (Next Day)",
        OfficialName = "United States Dollar (Next Day)",
        Symbol = null,
        NumericCode = "997",
        AlphabeticCode = "USN",
        Countries = new Dictionary<string, string>
        {
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// Uruguay Peso en Unidades Indexadas (URUIURUI)
    /// </summary>
    public static CurrencyInfo UruguayPesoEnUnidadesIndexadas { get; } = new CurrencyInfo
    {
        CommonName = "Uruguay Peso en Unidades Indexadas (URUIURUI)",
        NativeName = "Uruguay Peso en Unidades Indexadas (URUIURUI)",
        OfficialName = "Uruguay Peso en Unidades Indexadas (URUIURUI)",
        Symbol = null,
        NumericCode = "940",
        AlphabeticCode = "UYI",
        Countries = new Dictionary<string, string>
        {
            ["URY"] = "Oriental Republic of Uruguay",
        },
        MinorUnit = 0,
    };

    /// <summary>
    /// WIR euro
    /// </summary>
    /// <remarks>
    /// Complementary currency
    /// </remarks>
    public static CurrencyInfo WIREuro { get; } = new CurrencyInfo
    {
        CommonName = "WIR euro",
        NativeName = "WIR euro",
        OfficialName = "WIR euro",
        Symbol = null,
        NumericCode = "947",
        AlphabeticCode = "CHE",
        Countries = new Dictionary<string, string>
        {
            ["CHE"] = "Swiss Confederation",
        },
        MinorUnit = 2,
    };

    /// <summary>
    /// WIR franc
    /// </summary>
    /// <remarks>
    /// Complementary currency
    /// </remarks>
    public static CurrencyInfo WIRFranc { get; } = new CurrencyInfo
    {
        CommonName = "WIR franc",
        NativeName = "WIR franc",
        OfficialName = "WIR franc",
        Symbol = null,
        NumericCode = "948",
        AlphabeticCode = "CHW",
        Countries = new Dictionary<string, string>
        {
            ["CHE"] = "Swiss Confederation",
        },
        MinorUnit = 2,
    };
}
