// <auto-generated>
//     This file was automatically generated on 18 September 2025 at 09:53:40 UTC.
//     Any manual changes may cause errors and will be overwritten when regenerated.
// </auto-generated>

using System.Collections.ObjectModel;

#pragma warning disable IDE0130
namespace Firell.Standards;
#pragma warning restore IDE0130

#nullable enable

/// <summary>
/// Provides a collection of ISO 3166 country data and utility methods for retrieving country information based on various criteria.
/// </summary>
/// <remarks>
/// The <see cref="ISO3166"/> class contains a predefined collection of countries adhering to the ISO 3166-1 standard. It provides methods to retrieve country information by numeric, two-letter, or three-letter codes, as well as by region.</remarks>
public static partial class ISO3166
{
    /// <summary>
    /// Gets a read-only list of all defined countries.
    /// </summary>
    public static IReadOnlyList<CountryInfo> Countries { get; } = new CountryInfo[]
    {
        CountryInfo.Aruba,
        CountryInfo.Afghanistan,
        CountryInfo.Angola,
        CountryInfo.Anguilla,
        CountryInfo.ÅlandIslands,
        CountryInfo.Albania,
        CountryInfo.Andorra,
        CountryInfo.UnitedArabEmirates,
        CountryInfo.Argentina,
        CountryInfo.Armenia,
        CountryInfo.AmericanSamoa,
        CountryInfo.Antarctica,
        CountryInfo.FrenchSouthernAndAntarcticLands,
        CountryInfo.AntiguaAndBarbuda,
        CountryInfo.Australia,
        CountryInfo.Austria,
        CountryInfo.Azerbaijan,
        CountryInfo.Burundi,
        CountryInfo.Belgium,
        CountryInfo.Benin,
        CountryInfo.BurkinaFaso,
        CountryInfo.Bangladesh,
        CountryInfo.Bulgaria,
        CountryInfo.Bahrain,
        CountryInfo.Bahamas,
        CountryInfo.BosniaAndHerzegovina,
        CountryInfo.SaintBarthélemy,
        CountryInfo.SaintHelena,
        CountryInfo.Belarus,
        CountryInfo.Belize,
        CountryInfo.Bermuda,
        CountryInfo.Bolivia,
        CountryInfo.CaribbeanNetherlands,
        CountryInfo.Brazil,
        CountryInfo.Barbados,
        CountryInfo.Brunei,
        CountryInfo.Bhutan,
        CountryInfo.BouvetIsland,
        CountryInfo.Botswana,
        CountryInfo.CentralAfricanRepublic,
        CountryInfo.Canada,
        CountryInfo.CocosKeelingIslands,
        CountryInfo.Switzerland,
        CountryInfo.Chile,
        CountryInfo.China,
        CountryInfo.IvoryCoast,
        CountryInfo.Cameroon,
        CountryInfo.DRCongo,
        CountryInfo.RepublicOfTheCongo,
        CountryInfo.CookIslands,
        CountryInfo.Colombia,
        CountryInfo.Comoros,
        CountryInfo.CapeVerde,
        CountryInfo.CostaRica,
        CountryInfo.Cuba,
        CountryInfo.Curaçao,
        CountryInfo.ChristmasIsland,
        CountryInfo.CaymanIslands,
        CountryInfo.Cyprus,
        CountryInfo.Czechia,
        CountryInfo.Germany,
        CountryInfo.Djibouti,
        CountryInfo.Dominica,
        CountryInfo.Denmark,
        CountryInfo.DominicanRepublic,
        CountryInfo.Algeria,
        CountryInfo.Ecuador,
        CountryInfo.Egypt,
        CountryInfo.Eritrea,
        CountryInfo.WesternSahara,
        CountryInfo.Spain,
        CountryInfo.Estonia,
        CountryInfo.Ethiopia,
        CountryInfo.Finland,
        CountryInfo.Fiji,
        CountryInfo.FalklandIslands,
        CountryInfo.France,
        CountryInfo.FaroeIslands,
        CountryInfo.Micronesia,
        CountryInfo.Gabon,
        CountryInfo.UnitedKingdom,
        CountryInfo.Georgia,
        CountryInfo.Guernsey,
        CountryInfo.Ghana,
        CountryInfo.Gibraltar,
        CountryInfo.Guinea,
        CountryInfo.Guadeloupe,
        CountryInfo.Gambia,
        CountryInfo.GuineaBissau,
        CountryInfo.EquatorialGuinea,
        CountryInfo.Greece,
        CountryInfo.Grenada,
        CountryInfo.Greenland,
        CountryInfo.Guatemala,
        CountryInfo.FrenchGuiana,
        CountryInfo.Guam,
        CountryInfo.Guyana,
        CountryInfo.HongKong,
        CountryInfo.HeardIslandAndMcDonaldIslands,
        CountryInfo.Honduras,
        CountryInfo.Croatia,
        CountryInfo.Haiti,
        CountryInfo.Hungary,
        CountryInfo.Indonesia,
        CountryInfo.IsleOfMan,
        CountryInfo.India,
        CountryInfo.BritishIndianOceanTerritory,
        CountryInfo.Ireland,
        CountryInfo.Iran,
        CountryInfo.Iraq,
        CountryInfo.Iceland,
        CountryInfo.Israel,
        CountryInfo.Italy,
        CountryInfo.Jamaica,
        CountryInfo.Jersey,
        CountryInfo.Jordan,
        CountryInfo.Japan,
        CountryInfo.Kazakhstan,
        CountryInfo.Kenya,
        CountryInfo.Kyrgyzstan,
        CountryInfo.Cambodia,
        CountryInfo.Kiribati,
        CountryInfo.SaintKittsAndNevis,
        CountryInfo.SouthKorea,
        CountryInfo.Kosovo,
        CountryInfo.Kuwait,
        CountryInfo.Laos,
        CountryInfo.Lebanon,
        CountryInfo.Liberia,
        CountryInfo.Libya,
        CountryInfo.SaintLucia,
        CountryInfo.Liechtenstein,
        CountryInfo.SriLanka,
        CountryInfo.Lesotho,
        CountryInfo.Lithuania,
        CountryInfo.Luxembourg,
        CountryInfo.Latvia,
        CountryInfo.Macau,
        CountryInfo.SaintMartin,
        CountryInfo.Morocco,
        CountryInfo.Monaco,
        CountryInfo.Moldova,
        CountryInfo.Madagascar,
        CountryInfo.Maldives,
        CountryInfo.Mexico,
        CountryInfo.MarshallIslands,
        CountryInfo.NorthMacedonia,
        CountryInfo.Mali,
        CountryInfo.Malta,
        CountryInfo.Myanmar,
        CountryInfo.Montenegro,
        CountryInfo.Mongolia,
        CountryInfo.NorthernMarianaIslands,
        CountryInfo.Mozambique,
        CountryInfo.Mauritania,
        CountryInfo.Montserrat,
        CountryInfo.Martinique,
        CountryInfo.Mauritius,
        CountryInfo.Malawi,
        CountryInfo.Malaysia,
        CountryInfo.Mayotte,
        CountryInfo.Namibia,
        CountryInfo.NewCaledonia,
        CountryInfo.Niger,
        CountryInfo.NorfolkIsland,
        CountryInfo.Nigeria,
        CountryInfo.Nicaragua,
        CountryInfo.Niue,
        CountryInfo.Netherlands,
        CountryInfo.Norway,
        CountryInfo.Nepal,
        CountryInfo.Nauru,
        CountryInfo.NewZealand,
        CountryInfo.Oman,
        CountryInfo.Pakistan,
        CountryInfo.Panama,
        CountryInfo.PitcairnIslands,
        CountryInfo.Peru,
        CountryInfo.Philippines,
        CountryInfo.Palau,
        CountryInfo.PapuaNewGuinea,
        CountryInfo.Poland,
        CountryInfo.PuertoRico,
        CountryInfo.NorthKorea,
        CountryInfo.Portugal,
        CountryInfo.Paraguay,
        CountryInfo.Palestine,
        CountryInfo.FrenchPolynesia,
        CountryInfo.Qatar,
        CountryInfo.Réunion,
        CountryInfo.Romania,
        CountryInfo.Russia,
        CountryInfo.Rwanda,
        CountryInfo.SaudiArabia,
        CountryInfo.Sudan,
        CountryInfo.Senegal,
        CountryInfo.Singapore,
        CountryInfo.SouthGeorgia,
        CountryInfo.SvalbardAndJanMayen,
        CountryInfo.SolomonIslands,
        CountryInfo.SierraLeone,
        CountryInfo.ElSalvador,
        CountryInfo.SanMarino,
        CountryInfo.Somalia,
        CountryInfo.SaintPierreAndMiquelon,
        CountryInfo.Serbia,
        CountryInfo.SouthSudan,
        CountryInfo.SãoToméAndPríncipe,
        CountryInfo.Suriname,
        CountryInfo.Slovakia,
        CountryInfo.Slovenia,
        CountryInfo.Sweden,
        CountryInfo.Eswatini,
        CountryInfo.SintMaarten,
        CountryInfo.Seychelles,
        CountryInfo.Syria,
        CountryInfo.TurksAndCaicosIslands,
        CountryInfo.Chad,
        CountryInfo.Togo,
        CountryInfo.Thailand,
        CountryInfo.Tajikistan,
        CountryInfo.Tokelau,
        CountryInfo.Turkmenistan,
        CountryInfo.TimorLeste,
        CountryInfo.Tonga,
        CountryInfo.TrinidadAndTobago,
        CountryInfo.Tunisia,
        CountryInfo.Turkey,
        CountryInfo.Tuvalu,
        CountryInfo.Taiwan,
        CountryInfo.Tanzania,
        CountryInfo.Uganda,
        CountryInfo.Ukraine,
        CountryInfo.UnitedStatesMinorOutlyingIslands,
        CountryInfo.Uruguay,
        CountryInfo.UnitedStates,
        CountryInfo.Uzbekistan,
        CountryInfo.VaticanCity,
        CountryInfo.SaintVincentAndTheGrenadines,
        CountryInfo.Venezuela,
        CountryInfo.BritishVirginIslands,
        CountryInfo.UnitedStatesVirginIslands,
        CountryInfo.Vietnam,
        CountryInfo.Vanuatu,
        CountryInfo.WallisAndFutuna,
        CountryInfo.Samoa,
        CountryInfo.Yemen,
        CountryInfo.SouthAfrica,
        CountryInfo.Zambia,
        CountryInfo.Zimbabwe,
    };

    public static IReadOnlyCollection<string> Regions { get; } = new ReadOnlyCollection<string>
    ([
        "Africa",
        "Americas",
        "Antarctic",
        "Asia",
        "Europe",
        "Oceania",
    ]);

    /// <summary>
    /// Retrieves a country based on its numeric code.
    /// </summary>
    /// <param name="code">The three-digit ISO 3166-1 numeric country code.</param>
    /// <returns>A <see cref="CountryInfo"/> object if a matching country is found; otherwise, <see langword="null"/>.</returns>
    public static CountryInfo? GetByNumericCode(int code)
    {
        return Countries.FirstOrDefault(c => c.NumericCode.Equals(code.ToString().PadLeft(3, '0'), StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Retrieves a country based on its two-letter code.
    /// </summary>
    /// <param name="code">The two-letter ISO 3166-1 alpha-2 country code.</param>
    /// <returns>A <see cref="CountryInfo"/> object if a matching country is found; otherwise, <see langword="null"/>.</returns>
    public static CountryInfo? GetByTwoLetterCode(string code)
    {
        return Countries.FirstOrDefault(c => c.TwoLetterCode.Equals(code, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Retrieves a country based on its three-letter code.
    /// </summary>
    /// <param name="code">The three-letter ISO 3166-1 alpha-3 country code.</param>
    /// <returns>A <see cref="CountryInfo"/> object if a matching country is found; otherwise, <see langword="null"/>.</returns>
    public static CountryInfo? GetByThreeLetterCode(string code)
    {
        return Countries.FirstOrDefault(c => c.ThreeLetterCode.Equals(code, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Retrieves a read-only collection of countries that belong to the specified region.
    /// </summary>
    /// <param name="region">The region to filter countries by (e.g., "Europe", "Asia").</param>
    /// <returns>A read-only collection of <see cref="CountryInfo"/> objects that are located in the specified region.
    /// If no countries are found for the given region, an empty collection is returned.</returns>
    public static IReadOnlyCollection<CountryInfo> GetByRegion(string region)
    {
        return new ReadOnlyCollection<CountryInfo>(Countries.Where(c => c.Region.Equals(region, StringComparison.OrdinalIgnoreCase)).ToArray());
    }
}
