// <auto-generated>
//     This file was automatically generated on 18 September 2025 at 09:53:40 UTC.
//     Any manual changes may cause errors and will be overwritten when regenerated.
// </auto-generated>

#pragma warning disable IDE0130
namespace Firell.Standards;
#pragma warning restore IDE0130

/// <summary>
/// Represents the geographical regions of the world.
/// </summary>
public static partial class Region
{
    /// <summary>
    /// Represents the Africa region.
    /// </summary>
    public const string Africa = "Africa";

    /// <summary>
    /// Represents the Americas region.
    /// </summary>
    public const string Americas = "Americas";

    /// <summary>
    /// Represents the Antarctic region.
    /// </summary>
    public const string Antarctic = "Antarctic";

    /// <summary>
    /// Represents the Asia region.
    /// </summary>
    public const string Asia = "Asia";

    /// <summary>
    /// Represents the Europe region.
    /// </summary>
    public const string Europe = "Europe";

    /// <summary>
    /// Represents the Oceania region.
    /// </summary>
    public const string Oceania = "Oceania";
}
