// <auto-generated>
//     This file was automatically generated on 21 September 2025 at 11:42:34 UTC.
//     Any manual changes may cause errors and will be overwritten when regenerated.
// </auto-generated>

#pragma warning disable IDE0130
namespace Firell.Standards;
#pragma warning restore IDE0130

/// <summary>
/// Represents a geographical subregion within a larger region.
/// </summary>
public static partial class Subregion
{
    /// <summary>
    /// Represents the Australia and New Zealand subregion.
    /// </summary>
    public const string AustraliaAndNewZealand = "Australia and New Zealand";

    /// <summary>
    /// Represents the Caribbean subregion.
    /// </summary>
    public const string Caribbean = "Caribbean";

    /// <summary>
    /// Represents the Central America subregion.
    /// </summary>
    public const string CentralAmerica = "Central America";

    /// <summary>
    /// Represents the Central Asia subregion.
    /// </summary>
    public const string CentralAsia = "Central Asia";

    /// <summary>
    /// Represents the Central Europe subregion.
    /// </summary>
    public const string CentralEurope = "Central Europe";

    /// <summary>
    /// Represents the Eastern Africa subregion.
    /// </summary>
    public const string EasternAfrica = "Eastern Africa";

    /// <summary>
    /// Represents the Eastern Asia subregion.
    /// </summary>
    public const string EasternAsia = "Eastern Asia";

    /// <summary>
    /// Represents the Eastern Europe subregion.
    /// </summary>
    public const string EasternEurope = "Eastern Europe";

    /// <summary>
    /// Represents the Melanesia subregion.
    /// </summary>
    public const string Melanesia = "Melanesia";

    /// <summary>
    /// Represents the Micronesia subregion.
    /// </summary>
    public const string Micronesia = "Micronesia";

    /// <summary>
    /// Represents the Middle Africa subregion.
    /// </summary>
    public const string MiddleAfrica = "Middle Africa";

    /// <summary>
    /// Represents the North America subregion.
    /// </summary>
    public const string NorthAmerica = "North America";

    /// <summary>
    /// Represents the Northern Africa subregion.
    /// </summary>
    public const string NorthernAfrica = "Northern Africa";

    /// <summary>
    /// Represents the Northern Europe subregion.
    /// </summary>
    public const string NorthernEurope = "Northern Europe";

    /// <summary>
    /// Represents the Polynesia subregion.
    /// </summary>
    public const string Polynesia = "Polynesia";

    /// <summary>
    /// Represents the South America subregion.
    /// </summary>
    public const string SouthAmerica = "South America";

    /// <summary>
    /// Represents the South-Eastern Asia subregion.
    /// </summary>
    public const string SouthEasternAsia = "South-Eastern Asia";

    /// <summary>
    /// Represents the Southeast Europe subregion.
    /// </summary>
    public const string SoutheastEurope = "Southeast Europe";

    /// <summary>
    /// Represents the Southern Africa subregion.
    /// </summary>
    public const string SouthernAfrica = "Southern Africa";

    /// <summary>
    /// Represents the Southern Asia subregion.
    /// </summary>
    public const string SouthernAsia = "Southern Asia";

    /// <summary>
    /// Represents the Southern Europe subregion.
    /// </summary>
    public const string SouthernEurope = "Southern Europe";

    /// <summary>
    /// Represents the Western Africa subregion.
    /// </summary>
    public const string WesternAfrica = "Western Africa";

    /// <summary>
    /// Represents the Western Asia subregion.
    /// </summary>
    public const string WesternAsia = "Western Asia";

    /// <summary>
    /// Represents the Western Europe subregion.
    /// </summary>
    public const string WesternEurope = "Western Europe";
}
